### PR TITLE
Add label text to fields in KTL.js

### PR DESCRIPTION
**Pull request by CSWinnall**
This will change a fields label text in all or certain
view types it can either take 2 params [labelText], [tdfl] or just the _ltxt=LaelText to apply to all views

### CODE REVIEW

**Comment by cortexrd** [comment]
Just a few question or comments:

1. What's the main use of this feature?
2. I think **_lbl** would be more intuitive.
3. What will happen to all the kwds that depends on the label to do their job?  If the text changes dynamically... all may stop working.
4. We'd need to implement some method to synchronize the kwds execution so _lbl is done last.  Currently, the fact that it's being called last in the list doesn't guarantee this.
5. Do you plan to support ktlCond?

**Comment by CSWinnall** [comment]
HI Norm
The main use of this feature is that we can keep the field labels in the builder short and as we have a lot of forms with some long questions it means the builder data tables don't get really big.  The other use is that whenever we add a field to a view we don't have to keep updating the label in the builder.  We also have different labels depending on the format in the front end.

This does not affect your keywords as long as you use the label you see in the builder as we are only changing the text in the dom NOT the Knack object.  We have been using this extensively in our app for months now with no issues with keywords.

ktlCond could be added & _lbl is fine.

Craig

**Comment by cortexrd** [comment]
Ok, now I can see the benefit of this.

BTW, about this:  "_This does not affect your keywords as long as you use the label you see in the builder as we are only changing the text in the dom NOT the Knack object._"

You're right, except I'm not 100% sure what will happen if you're using a jQuery selector that relies on the label to find its value...

But in worst case, we'll deal with this later, and document appropriately.

Can you just change to _lbl please and I'll merge.

**Comment by cortexrd** [comment]
ktlCond will wait.

**Review by cortexrd — APPROVED** [review]
Changed to _lbl, no need to do it.
All looks good.

**Pull request merged**
