### PR TITLE
Fix/req-field-keywords-independant-of-view-keywords

### PR DESCRIPTION
**Pull request by CSWinnall**

### CODE REVIEW

**Comment by Greenlight88** [comment]
Amazing! Can I test? What version would I use? Thanks Craig

**Comment by CSWinnall** [comment]
It's possibly available in beta but it's not available in Prod yet on any version.

**Comment by cortexrd** [comment]
Hi guys,

I'll merge that tomorrow and do a release in prod.  Stay tuned...
Thanks Craig!

Norm

**Comment by cortexrd** [comment]
Released in KTL v0.29.6

Norm

**Comment by Greenlight88** [comment]
Awesome, I'll test this week

**Comment by Greenlight88** [comment]
Hey Craig and Norm,

I tested this just now, did not work for me - I tested two field types, a numeric field and a drop down - confirming I updated to KTL v0.29.6

_I may be misunderstanding the nature of the the fix here_

In my use case we have fields on a form that are displayed or not displayed based on other data on the form

We use Knacks native interface to achieve that part

Where the fields are visible on this form we would like that field to be required - we would like to use KTL for that second part.

Why not just make it a required field, you ask? Well there may be other types of forms where we would like the field to be visible but not required so this keyword _req would seem to offer a work around almost a dynamic required if 

Anyway in my tests and as in the previous versions, when a field is set as required in KTLx but not visible the form cannot be submitted

screenshot of one of my tests below - note I also tried using the field reference in case that worked, no dice

First shot here shows the _req function working when field is visible

Screenshot 2025-01-18 230100


And here when field is not visible on form, the submit button is washed out - Oucome set to Not a Lead

Screenshot 2025-01-18 230217

**Comment by amandajane-mo** [comment]
Hi,

You need to update to KTL ver 0.29.7.

Please report back how you get on.

Thanks
Amanda

**Comment by Greenlight88** [comment]
Hi Amanda,

Thank you  same result 0.29.7 :(

I had this thought while testing though - the knack interface lets you update the label of a field dynamically - So I thought if I get knack to change the label when field is not required then the KTL _req function might not apply...

But that didn't work - it still recognised the field even though it had a different label name now - but I thought that might be meaningful to you, why wouldn't that work? See below screenshots - I set up a new form so it wouldnt be affected by anything else

It feels like the knack changes either to rename the label or to hide / show the field, happen _after_KTL actions

The KTL code here is _req=Enquiry Value (Required)

Screenshot 2025-01-19 220119
Screenshot 2025-01-19 220151
 intervention

And tried also to make the field not visible using knack, same washed out button, tried both renaming the label and making field not visible

**Comment by amandajane-mo** [comment]
Have you tried using the field id instead?

**Comment by Greenlight88** [comment]
Hi Amanda - I tried that just now, same result

Screenshot 2025-01-20 094025
Screenshot 2025-01-20 094051
Screenshot 2025-01-20 094114
Screenshot 2025-01-20 094201

**Comment by CSWinnall** [comment]
Hi @Greenlight88 
Sorry this isn't working for you.  Could you please give Amanda and I access to that form?  Or could we set up a meeting if that would be better to take a look?
You can email me craig.winnall@gmail.com
Craig

**Comment by CSWinnall** [comment]
I think this has been fixed in this PR #441

**Comment by CSWinnall** [comment]
Hi @Greenlight88 

This should now be fixed in 0.29.10 please give it a try and let me know.

Craig

**Comment by Greenlight88** [comment]
Yes it works! This is beautiful

**Pull request merged**
