### PR TITLE
Fix tooltip code and improve user experience

### PR DESCRIPTION
**Pull request by CSWinnall**
Removed the rudundent call to addTooltipToFields for lists
Made the tooltip for forms more specific

### CODE REVIEW

**Comment by cortexrd** [comment]
Craig,

I was about to merge your PR, but for some reason, I see hundreds of recent code changes, instead of just your stuff.  It's the first time I see this, and not sure what to do.

Can you try to see on your side if you can get the latest dev branch update and re-instate your changes there?

I will discuss with Charles at 10am to see find out what happened and how we can avoid this in the future.  I'll keep you informed.

Norm

**Comment by CSWinnall** [comment]
Ok I'll take a look.  I don't think I did anything different.

**Comment by cortexrd** [comment]
It's Charles who did a rebase of his branch on dev.  This has modified the history, and explains why your code got "lost" in a huge amount of changes since you've branched from an "old" version of dev.
Apparently, we should always rebase our branch on dev before doing a pull request. I didn't know that either.

And to be honest… I'm not even sure I full understand what all this means.  I need to study a bit more on this.

Norm

**Comment by cortexrd** [comment]
Yes, you need to copy your code in a temporary file.
Then re-create a new branch from a fresh pull of dev, to get all the latest code.
Paste your new code in that branch, commit and do a new pull request.
For the existing PR, we will eventually delete it.

That should work.

Norm

**Comment by cortexrd** [comment]
Craig, I've merged your new PR.  I can now delete this one - right?
Norm

**Comment by CSWinnall** [comment]
Yes please

**Pull request closed without merging**
