### PR TITLE
Add disableGrid function to KTL.js

### PR DESCRIPTION
**Pull request by CSWinnall**
A simple function that will disable all cells on a grid will take ktlRoles

### CODE REVIEW

**Review by cortexrd — CHANGES_REQUESTED** [review]
I've done a few tests and found that a link field is not disabled when in a Details view. 
 Action Links are disabled but not plain link fields.

In a form, I don't see any effect with my current setup.  I tried adding a link field, but it doesn't get disabled.  Not sure how to test this one.

Also, we use single quotes and backticks in the KTL.  I see some "a" and "href".

Other than that, the keyword works well.
I like the Object Destructuring pattern.  Didn't know about that one!

**Comment by CSWinnall** [comment]
Hi Norm

Interesting about the details view. I'll look into it, I tried it with both view links and action links is this a different type of link?.

With the form the only thing I could think of turning off is the add option which I believe it disables.  I could get it to disable added links too.

Craig

**Comment by CSWinnall** [comment]
Hi Norm

Interesting about the details view. I'll look into it, I tried it with both view links and action links is this a different type of link?.

With the form the only thing I could think of turning off is the add option which I believe it disables.  I could get it to disable added links too.

Craig

**Comment by CSWinnall** [comment]
I see what you mean about link fields.  I'll get on 8t.

**Comment by cortexrd** [comment]
Not sure about forms: what should the _dv do...  Do you see any real use?
About disabling the Submit button, I see no value added here.  Might as well just hide the whole view.

I let you decide.
Norm

**Comment by cortexrd** [comment]
Actually, disabling a whole form could be useful, based on a ktlCond.  Ex: if a checkbox "I accept all terms and conditions" is not checked to Yes, the form is disabled and nothing can be entered or Submitted.  All fields would be grayed out in this case to indicate they are disabled.

ND

**Review by CSWinnall — COMMENTED** [review]
Hi Norm 

This should now work as expected.  The ktlCond for forms is going to take me a bit longer to get my head around.  
As it stands it will disable any add an option to a select in a form and any 'a' links that a user has added in a title copy.
We have a use case where some users can add to selects and some can't.
C

**Review by cortexrd — APPROVED** [review]
Good feature, thank you.

**Pull request merged**
